SELECT
    CL.COUNTRY      AS ULKE,
    INV.DATE_       AS FATURA_TARIHI,
    INV.FICHENO     AS FATURA_NO,
    CL.CODE         AS CARI_KOD,
    CL.DEFINITION_  AS CARI_UNVAN,

    CASE 
        WHEN INV.TRCURR = 0 THEN INV.NETTOTAL
        ELSE INV.TRNET
    END             AS FATURA_TUTARI_DOVIZLI,

    INV.NETTOTAL    AS FATURA_TUTARI_TL,

    CASE INV.TRCURR
        WHEN 0  THEN 'TL'
        WHEN 1  THEN 'USD'
        WHEN 20 THEN 'EUR'
        WHEN 10 THEN 'GBP'
        ELSE STR(INV.TRCURR)
    END             AS DOVIZ_BIRIMI,

    IIF.CUSTDOCNO   AS GB_NO,
    IIF.RESULTDATE0 AS INTAC_TARIHI,

    (
        SELECT 
            SUM(EMF_SUB.DEBIT - EMF_SUB.CREDIT)
        FROM LG_{FIRMNR}_01_EMFLINE EMF_SUB
        INNER JOIN LG_{FIRMNR}_EMUHACC ACC_SUB
            ON ACC_SUB.LOGICALREF = EMF_SUB.ACCOUNTREF
        WHERE
            EMF_SUB.ACCFICHEREF = INV.ACCFICHEREF
            AND (
                ACC_SUB.CODE LIKE '12%' 
                OR ACC_SUB.CODE LIKE '32%'
            )
    ) AS MUHASEBE_TUTARI,

    INV.TRADINGGRP  AS TICARI_ISLEM_GRUBU

FROM LG_{FIRMNR}_01_INVOICE INV
LEFT JOIN LG_{FIRMNR}_CLCARD CL
    ON CL.LOGICALREF = INV.CLIENTREF
INNER JOIN LG_{FIRMNR}_01_INVEXIMINFO IIF
    ON IIF.INVOICEREF = INV.LOGICALREF

WHERE
    INV.DATE_ BETWEEN '2026-01-01' AND '2026-12-31'
    AND INV.CANCELLED = 0
