SELECT 
    AY_NO, 
    AYLAR, 
    KDV_ORANI,
    SUM(SAT_MATRAH) AS SATINALMA_MATRAH,
    SUM(SAT_KDV) AS SATINALMA_KDV,
    SUM(SAT_FF_ART_MAT) AS SAT_FF_ARTIRILACAK_MATRAH,
    SUM(SAT_FF_ART_KDV) AS SAT_FF_ARTIRILACAK_KDV,
    SUM(SAT_IADE_MAT) AS SATINALMA_IADE_MATRAH,
    SUM(SAT_IADE_KDV) AS SATINALMA_IADE_KDV,
    SUM(SAT_FF_AZALT_MAT) AS SAT_FF_AZALTILACAK_MATRAH,
    SUM(SAT_FF_AZALT_KDV) AS SAT_FF_AZALTILACAK_KDV,
    SUM(STIS_MATRAH) AS SATIS_MATRAH,
    SUM(STIS_KDV) AS SATIS_KDV,
    SUM(STIS_FF_ART_MAT) AS SATIS_FF_ARTIRILACAK_MATRAH,
    SUM(STIS_FF_ART_KDV) AS SATIS_FF_ARTIRILACAK_KDV,
    SUM(STIS_IADE_MAT) AS SATIS_IADE_MATRAH,
    SUM(STIS_IADE_KDV) AS SATIS_IADE_KDV,
    SUM(STIS_FF_AZALT_MAT) AS SATIS_FF_AZALTILACAK_MATRAH,
    SUM(STIS_FF_AZALT_KDV) AS SATIS_FF_AZALTILACAK_KDV
FROM (
    -- 1. FATURALAR (Karma Koli hesaplanıp normal oranlara yedirildi)
    SELECT 
        MONTH(I.DATE_) AS AY_NO,
        (CASE MONTH(I.DATE_) WHEN 1 THEN 'Ocak' WHEN 2 THEN 'Şubat' WHEN 3 THEN 'Mart' WHEN 4 THEN 'Nisan' WHEN 5 THEN 'Mayıs' WHEN 6 THEN 'Haziran' WHEN 7 THEN 'Temmuz' WHEN 8 THEN 'Ağustos' WHEN 9 THEN 'Eylül' WHEN 10 THEN 'Ekim' WHEN 11 THEN 'Kasım' WHEN 12 THEN 'Aralık' ELSE '' END) + ' 2026' AS AYLAR,
        
        CAST(
            CASE WHEN L.VAT = 0 AND L.VATMATRAH > 0 AND ITM.CARDTYPE = 2 
                 THEN ROUND((L.VATAMNT / L.VATMATRAH) * 100, 0) 
                 ELSE L.VAT 
            END AS INT
        ) AS KDV_ORANI,

        (CASE WHEN I.TRCODE IN (1,4) AND L.LINETYPE <> 1 THEN L.VATMATRAH ELSE 0 END) AS SAT_MATRAH,
        (CASE WHEN I.TRCODE IN (1,4) AND L.LINETYPE <> 1 THEN L.VATAMNT ELSE 0 END) AS SAT_KDV,
        (CASE WHEN I.TRCODE = 13 AND I.DECPRDIFF = 0 THEN L.VATMATRAH ELSE 0 END) AS SAT_FF_ART_MAT,
        (CASE WHEN I.TRCODE = 13 AND I.DECPRDIFF = 0 THEN L.VATAMNT ELSE 0 END) AS SAT_FF_ART_KDV,
        (CASE WHEN I.TRCODE = 6 THEN L.VATMATRAH ELSE 0 END) AS SAT_IADE_MAT,
        (CASE WHEN I.TRCODE = 6 THEN L.VATAMNT ELSE 0 END) AS SAT_IADE_KDV,
        (CASE WHEN I.TRCODE = 13 AND I.DECPRDIFF = 1 THEN L.VATMATRAH ELSE 0 END) AS SAT_FF_AZALT_MAT,
        (CASE WHEN I.TRCODE = 13 AND I.DECPRDIFF = 1 THEN L.VATAMNT ELSE 0 END) AS SAT_FF_AZALT_KDV,
        (CASE WHEN I.TRCODE IN (8,9) AND L.LINETYPE <> 1 THEN L.VATMATRAH ELSE 0 END) AS STIS_MATRAH,
        (CASE WHEN I.TRCODE IN (8,9) AND L.LINETYPE <> 1 THEN L.VATAMNT ELSE 0 END) AS STIS_KDV,
        (CASE WHEN I.TRCODE = 14 AND I.DECPRDIFF = 0 THEN L.VATMATRAH ELSE 0 END) AS STIS_FF_ART_MAT,
        (CASE WHEN I.TRCODE = 14 AND I.DECPRDIFF = 0 THEN L.VATAMNT ELSE 0 END) AS STIS_FF_ART_KDV,
        (CASE WHEN I.TRCODE = 3 THEN L.VATMATRAH ELSE 0 END) AS STIS_IADE_MAT,
        (CASE WHEN I.TRCODE = 3 THEN L.VATAMNT ELSE 0 END) AS STIS_IADE_KDV,
        (CASE WHEN I.TRCODE = 14 AND I.DECPRDIFF = 1 THEN L.VATMATRAH ELSE 0 END) AS STIS_FF_AZALT_MAT,
        (CASE WHEN I.TRCODE = 14 AND I.DECPRDIFF = 1 THEN L.VATAMNT ELSE 0 END) AS STIS_FF_AZALT_KDV
    FROM LG_{FIRMNR}_{PERIODNRPP}_INVOICE I WITH(NOLOCK)
    INNER JOIN LG_{FIRMNR}_{PERIODNRPP}_STLINE L WITH(NOLOCK) ON I.LOGICALREF = L.INVOICEREF
    LEFT JOIN LG_{FIRMNR}_ITEMS ITM WITH(NOLOCK) ON L.STOCKREF = ITM.LOGICALREF
    WHERE I.DATE_ BETWEEN '20260101' AND '20261231' AND I.CANCELLED = 0 AND L.LINETYPE NOT IN (2,3,7)

    UNION ALL

    -- 2. CARİ FİŞLER (46 - Sadece Matraha Gömüldü)
    SELECT 
        MONTH(CLF.DATE_), 
        (CASE MONTH(CLF.DATE_) WHEN 1 THEN 'Ocak' WHEN 2 THEN 'Şubat' WHEN 3 THEN 'Mart' WHEN 4 THEN 'Nisan' WHEN 5 THEN 'Mayıs' WHEN 6 THEN 'Haziran' WHEN 7 THEN 'Temmuz' WHEN 8 THEN 'Ağustos' WHEN 9 THEN 'Eylül' WHEN 10 THEN 'Ekim' WHEN 11 THEN 'Kasım' WHEN 12 THEN 'Aralık' ELSE '' END) + ' 2026',
        CAST(CLF.VATRATE AS INT),
        CLF.AMOUNT, (CLF.AMOUNT * CLF.VATRATE / 100), 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    FROM LG_{FIRMNR}_{PERIODNRPP}_CLFLINE CLF WITH(NOLOCK)
    WHERE CLF.TRCODE = 46 AND CLF.CANCELLED = 0 AND CLF.DATE_ BETWEEN '20260101' AND '20261231'

) AS TBL
GROUP BY AY_NO, AYLAR, KDV_ORANI
