SELECT 
    CLC.CODE AS [CARİ_HESAP_KODU], 
    CLC.DEFINITION_ AS [CARİ_HESAP_AÇIKLAMASI], 
    ACC.CODE AS [MUHASEBE_HESAP_KODU],
    ACC.DEFINITION_ AS [MUHASEBE_HESAP_AÇIKLAMASI],

    -- ÖN MUHASEBE BAKİYESİ
    ISNULL(OM.BAKIYE,0) AS [ÖN_MUHASEBE_BAKİYE],

    -- GENEL MUHASEBE BAKİYESİ
    ISNULL(GM.BAKIYE,0) AS [GENEL_MUHASEBE_BAKİYE],

    -- FARK
    ROUND(ISNULL(OM.BAKIYE,0) - ISNULL(GM.BAKIYE,0),2) AS [BAKİYE_FARKI]

FROM LG_{FIRMNR}_CLCARD CLC WITH(NOLOCK)

-- DOĞRU MUHASEBE HESABI
OUTER APPLY (
    SELECT TOP 1 
        ACC2.LOGICALREF,
        ACC2.CODE,
        ACC2.DEFINITION_
    FROM LG_{FIRMNR}_CRDACREF CRA WITH(NOLOCK)
    INNER JOIN LG_{FIRMNR}_EMUHACC ACC2 WITH(NOLOCK)
        ON CRA.ACCOUNTREF = ACC2.LOGICALREF
    WHERE 
        CRA.CARDREF = CLC.LOGICALREF
        AND CRA.TYP = 1
        AND (ACC2.CODE LIKE '120%' OR ACC2.CODE LIKE '320%') -- sadece cari hesaplar
    ORDER BY ACC2.CODE -- en uygun hesabı seç
) ACC

--  ÖN MUHASEBE
OUTER APPLY (
    SELECT 
        ROUND(SUM(CASE WHEN CLFL.SIGN = 0 THEN CLFL.AMOUNT ELSE -CLFL.AMOUNT END),2) AS BAKIYE
    FROM LG_{FIRMNR}_{PERIODNRPP}_CLFLINE CLFL WITH(NOLOCK)
    WHERE 
        CLFL.CLIENTREF = CLC.LOGICALREF 
        AND CLFL.CANCELLED = 0
        AND CLFL.PAIDINCASH = 0 
) OM

-- GENEL MUHASEBE
OUTER APPLY (
    SELECT 
        ROUND(SUM(EMFL.DEBIT - EMFL.CREDIT),2) AS BAKIYE
    FROM LG_{FIRMNR}_{PERIODNRPP}_EMFLINE EMFL WITH(NOLOCK)
    WHERE 
        EMFL.ACCOUNTREF = ACC.LOGICALREF
        AND EMFL.CANCELLED = 0
) GM

WHERE 
    CLC.ACTIVE = 0
